FROM rocker/shiny-verse:4.3.0

# Install Ubuntu packages
RUN apt-get update && apt-get install -y \
    libcurl4-gnutls-dev \
    libssl-dev

# Workaround for renv cache
RUN mkdir /.cache
RUN chmod 777 /.cache

WORKDIR /code

# Install renv
RUN install2.r --error \
    renv

# Copy application code
COPY . .

# Install dependencies
RUN Rscript -e 'options(renv.config.cache.enabled = FALSE); renv::restore(prompt = FALSE)'

# Make the ShinyApp available at port 80
EXPOSE 3838

CMD ["R", "-e", "shiny::runApp('/app', host = '0.0.0.0', port = 3838)"]